# 1. The Storage Claim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
spec:
  accessModes:
    - ReadWriteOnce # Standard for block storage
  resources:
    requests:
      storage: 1Gi
---
# 2. The Application (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deploy
spec:
  replicas: 1 # Keep as 1. If you scale up, all pods try to write to the SAME disk (which usually fails with RWO)
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: web-storage
      volumes:
      - name: web-storage
        persistentVolumeClaim:
          claimName: web-pvc
---
# 3. The Network Exposure (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: web-lb
spec:
  selector:
    app: my-web-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
